baseURL = "https://page-of-paige.netlify.app"
languageCode = "en-us"
title = "Paige's Portfolio"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "paige-downey.jpg"
  author = "Paige Downey"
  description = "My portfolio website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "PaigeCD"
  Email         = "paigedown05@gmail.com"
  LinkedIn      = "paigecd"

## Main Menu
[[menu.main]]
  name = "experience"
  weight = 100
  identifier = "experience"
  url = "/experience/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"